version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: skyshield_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skyshield_frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
